### ISSUE TITLE
Fields created_by and updated_by

### ISSUE THREAD

**Issue by Khludev** [wikichua/simplecontrolpanel#5]
I assume that the identifier will always be stored here.
Does it make sense to type the text field?
I think we need BigInteger.

**Comment by wikichua** [comment]
yeah, bigInteger or text input can be changed on the config file. im removing the input part because in the controller, the created_by or updated_by will be stored automatically on auth()->id(). depends on your usage. usually if the records belongs to somebody, i will create another field for it. 
example author_id in books table :D
